POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "exampleUser",
    "email": "user@example.com",
    "password": "examplePassword"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "examplePassword"
}


###untuk homeRoutes

###
GET http://localhost:3000/user/:id
Authorization: Bearer (token here)

###
GET http://localhost:9090/get-data

###
POST http://localhost:9090/upload-data

###
DELETE http://localhost:3000/logout
Authorization: Bearer (token here)


